In [35]:
#load processed_Input_A1_1.csv file to df
import pandas as pd
import numpy as np

telemetry = pd.read_csv('processed_Input_A1_1.csv')
path_data = pd.read_csv('Solution_first_lap_equidistant.csv')

In [36]:
def calculate_distance(p1, p2):
    """
    Calculate Euclidean distance between two 3D points.
    """
    return np.linalg.norm(np.array(p1) - np.array(p2))

In [37]:
telemetry=telemetry.dropna()
telemetry.drop(columns=['fuel capacity'],inplace=True)
telemetry

,tick,timestamp,speed_kmh,throttle,brake,rpm,fuel,charge_rem,boost,clutch,pos_x,pos_y,pos_z,loop_count,distance,cumulative_distance,distance_to_lap,time_to_lap
0,1.0,0 days 00:00:00.008413806,0.00000,0.0,255.0,1540.0000,100.000000,100.000000,0.408447,1.0,0.0000,0.000000,0.00000,0,0.000000,0.000000,183.477914,14.439533
1,2.0,0 days 00:00:00.019754230,0.00000,0.0,255.0,1539.0000,100.000000,100.000000,0.408447,1.0,0.0000,0.000000,0.00000,0,0.000000,0.000000,183.477914,14.428193
2,3.0,0 days 00:00:00.036326945,0.00000,0.0,255.0,1538.0000,100.000000,100.000000,0.408447,1.0,0.0000,0.000000,0.00000,0,0.000000,0.000000,183.477914,14.411620
3,4.0,0 days 00:00:00.053150289,0.00000,0.0,255.0,1537.0000,100.000000,100.000000,0.408447,1.0,0.0000,0.000000,0.00000,0,0.000000,0.000000,183.477914,14.394796
4,5.0,0 days 00:00:00.069594373,0.00000,0.0,255.0,1535.0000,100.000000,100.000000,0.408447,1.0,0.0000,0.000000,0.00000,0,0.000000,0.000000,183.477914,14.378352
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
225008,225009.0,0 days 01:02:33.972794072,192.95880,254.0,0.0,6337.2285,9.411766,9.411766,1.789592,0.0,2.5552,0.440861,-32.86284,31,0.894229,166285.981117,3.585223,0.065272
225009,225010.0,0 days 01:02:33.989597047,193.19121,255.0,0.0,6342.0015,9.411766,9.411766,1.789022,0.0,2.0482,0.424494,-32.12510,31,0.895308,166286.876426,2.689914,0.048470
225010,225011.0,0 days 01:02:34.004781523,193.34897,255.0,0.0,6346.9663,9.613445,9.613445,1.788308,0.0,1.5404,0.408306,-31.38695,31,0.896096,166287.772522,1.793818,0.033285
225011,225012.0,0 days 01:02:34.020729389,193.45038,0.0,0.0,6344.1780,9.613445,9.613445,1.787086,0.0,1.0336,0.392460,-30.64760,31,0.896513,166288.669035,0.897305,0.017337
225012,225013.0,0 days 01:02:34.038066554,193.63179,0.0,0.0,6324.2770,9.613445,9.613445,1.785097,0.0,0.5265,0.376396,-29.90750,32,0.897305,166289.566340,0.000000,0.000000

In [38]:


# Calculate cumulative distance in the path data for future use
def calculate_path_distances(df):
    distances = np.sqrt(
        np.diff(df['pos_x'], prepend=df['pos_x'].iloc[0])**2 +
        np.diff(df['pos_y'], prepend=df['pos_y'].iloc[0])**2 +
        np.diff(df['pos_z'], prepend=df['pos_z'].iloc[0])**2
    )
    df['cumulative_distance'] = np.cumsum(distances)
    return df

path_data = calculate_path_distances(path_data)

# Assuming path_data has equal distances along the lap
total_path_distance = path_data['cumulative_distance'].iloc[-1]
total_path_distance

7357.738604401279

In [39]:
# pos_x_0 = path_data['pos_x'].iloc[0]
# pos_y_0 = path_data['pos_y'].iloc[0]
# pos_z_0 = path_data['pos_z'].iloc[0]

# path_data['pos_x'] = path_data['pos_x'] - pos_x_0
# path_data['pos_y'] = path_data['pos_y'] - pos_y_0
# path_data['pos_z'] = path_data['pos_z'] - pos_z_0

In [40]:
path_data

          pos_x      pos_y       pos_z  cumulative_distance
0   -123.696860 -19.997458 -125.194150             0.000000
1   -108.939890 -19.990359 -126.184591            14.790172
2    -94.183243 -19.986835 -127.180110            29.580361
3    -79.426458 -19.967782 -128.173360            44.370547
4    -64.667344 -19.957857 -129.130886            59.160693
..          ...        ...         ...                  ...
495 -189.935190 -19.976254 -106.509548          7298.577888
496 -175.171253 -19.997446 -107.389977          7313.368069
497 -160.410824 -19.973020 -108.327063          7328.158235
498 -145.653781 -19.982276 -109.316581          7342.948419
499 -130.897700 -19.991636 -110.320360          7357.738604

[500 rows x 4 columns]

In [42]:
def calculate_distance(p1, p2):
    """Calculate Euclidean distance between two 3D points."""
    return np.linalg.norm(np.array(p1) - np.array(p2))

def calculate_cumulative_distance(telemetry):
    """Calculate cumulative distance covered by the vehicle."""
    cumulative_distances = [0]  # Start with 0 for the initial position

    for i in range(1, len(telemetry)):
        prev_point = telemetry.iloc[i - 1][['pos_x', 'pos_y', 'pos_z']].values
        curr_point = telemetry.iloc[i][['pos_x', 'pos_y', 'pos_z']].values
        distance = calculate_distance(prev_point, curr_point)
        cumulative_distances.append(cumulative_distances[-1] + distance)

    telemetry['cumulative_distance'] = cumulative_distances
    return telemetry

# Calculate the cumulative distance
telemetry = calculate_cumulative_distance(telemetry)

In [60]:
def preprocess_data(telemetry: pd.DataFrame) -> pd.DataFrame:

    try:
        drop_col=['Unnamed: 0','packet id', 'gear_curr', 'gear_sugg','battery_max','tyre_diam_fl', 'tyre_diam_fr', 'tyre_diam_rl', 'tyre_diam_rr',
        'tyre_speed_fl', 'tyre_speed_fr', 'tyre_speed_rl', 'tyre_speed_rr',
        'time_of_day_ms', 'rpm_warning', 'rpm_rev_limiter', 'speed_top',
        'clutch_engaged', 'rpm_after_clutch', 'oil_temp',
        'water_temp', 'oil_pressure', 'ride_height', 'tyre_temp_fl',
        'tyre_temp_fr', 'suspension_fl', 'suspension_fr', 'tyre_temp_rl',
        'tyre_temp_rr', 'suspension_rl', 'suspension_rr', 'gear_1', 'gear_2',
        'gear_3', 'gear_4', 'gear_5', 'gear_6', 'gear_7', 'gear_8', 'gear_9',
        'vel_x', 'vel_y', 'vel_z', 'rot_x', 'rot_y', 'rot_z', 'vel_ang_x',
        'vel_ang_y', 'vel_ang_z', 'rotx_x', 'unknown_bits_0', 'unknown_bits_1',
        'unknown_bits_2', 'unknown_float_0', 'unknown_float_1',
        'unknown_float_2', 'unknown_float_3', 'unknown_float_4',
        'unknown_float_5', 'unknown_float_6', 'unknown_float_7',
        'unknown_float_8', 'unknown_float_9', 'unknown_float_10',
        'unknown_float_11'
        ]
        telemetry.drop(drop_col, axis=1, inplace=True)
    except: 
        pass
    telemetry['pos_x_new'] = telemetry['pos_x'] - telemetry['pos_x'][0]
    telemetry['pos_y_new'] = telemetry['pos_y'] - telemetry['pos_y'][0]
    telemetry['pos_z_new'] = telemetry['pos_z'] - telemetry['pos_z'][0]
    
    

    def calculate_distance(p1, p2):
        """
        Calculate Euclidean distance between two 3D points.
        """
        return np.linalg.norm(np.array(p1) - np.array(p2))

    def count_loops(df, max_distance=30, min_distance=0, ignore_ticks=5000):
        """
        Count the number of loops in the 3D trajectory.

        Args:
            df (pd.DataFrame): DataFrame with x, y, z coordinates.
            max_distance (float): Maximum distance to be considered a loop closure.
            min_distance (float): Minimum distance to be considered a loop closure.
            ignore_ticks (int): Number of ticks to ignore after a loop closure.

        Returns:
            pd.DataFrame: DataFrame with an updated 'loop_count' column.
        """

        points = df[['pos_x_new', 'pos_y_new', 'pos_z_new']].values
        start_point = points[0]  # Reference starting point

        loop_count = 0  # Initialize loop counter
        ignore_until = 0  # To skip points after a detected loop

        # List to store the loop count for each row
        loop_counts = []

        # Iterate through each point
        for i in range(len(points)):
            if i < ignore_until:
                # If within the ignore window, reuse the last loop count
                loop_counts.append(loop_count)
                continue

            # Calculate distance from current point to the starting point
            distance = calculate_distance(start_point, points[i])

            if min_distance < distance < max_distance:
                # If a loop is detected, increment the loop counter
                loop_count += 1
                ignore_until = i + ignore_ticks  # Set the next point to ignore

            # Store the current loop count for this row
            loop_counts.append(loop_count)

        # Add the loop counts as a new column to the DataFrame
        df['loop_count'] = loop_counts
        return df

    # Example usage
    # telemetry = pd.read_csv('telemetry.csv')  # Load your telemetry data
    telemetry = count_loops(telemetry)  


    def calculate_cumulative_distance_telemetry(telemetry):
        """
        Calculate the cumulative distance travelled by the vehicle.

        Args:
            telemetry (pd.DataFrame): DataFrame with x, y, z coordinates.

        Returns:
            pd.DataFrame: DataFrame
        """
        
        # Calculate the distance between consecutive points
        telemetry['distance'] = telemetry[['pos_x_new', 'pos_y_new', 'pos_z_new']].diff().apply(np.linalg.norm, axis=1)

        # Calculate the cumulative distance
        telemetry['cumulative_distance'] = telemetry['distance'].cumsum()
        telemetry = telemetry.fillna(0)  # Fill NaN values with 0
        

        return telemetry

    def calculate_time_to_lap_telemetry(telemetry):
        telemetry['timestamp'] = pd.to_timedelta(telemetry['timestamp'], errors='coerce')
        # Initialize the new column with NaNs
        telemetry['time_to_lap'] = np.nan

        # Get unique loop counts
        unique_loop_counts = telemetry['loop_count'].unique()

        # Iterate over the unique loop counts
        for i in range(len(unique_loop_counts) - 1):
            current_loop_count = unique_loop_counts[i]
            next_loop_count = unique_loop_counts[i + 1]

            # Get the indices for the current loop count
            current_indices = telemetry[telemetry['loop_count'] == current_loop_count].index

            # Get the timestamp of the first row of the next loop count
            next_loop_start_index = telemetry[telemetry['loop_count'] == next_loop_count].index[0]
            next_loop_start_time = telemetry.loc[next_loop_start_index, 'timestamp']

            # Calculate the time to the next lap for the current loop count
            telemetry.loc[current_indices, 'time_to_lap'] = (next_loop_start_time - telemetry.loc[current_indices, 'timestamp']).dt.total_seconds()

        # Handle the last loop count (set time to lap as 0)
        last_loop_indices = telemetry[telemetry['loop_count'] == unique_loop_counts[-1]].index
        telemetry.loc[last_loop_indices, 'time_to_lap'] = 0

        return telemetry


    def calculate_distance_to_lap_telemetry(telemetry):
        """
        Calculate the distance to the next lap for each row in the telemetry DataFrame.
        
        Parameters:
        telemetry (pd.DataFrame): The telemetry data containing 'loop_count' and 'cumulative_distance' columns.
        
        Returns:
        pd.DataFrame: The telemetry DataFrame with an additional 'distance_to_lap' column.
        """
        # Initialize the new column with zeros
        telemetry['distance_to_lap'] = 0

        # Get unique loop counts
        unique_loop_counts = telemetry['loop_count'].unique()

        # Iterate over the unique loop counts
        for i in range(len(unique_loop_counts) - 1):
            current_loop_count = unique_loop_counts[i]
            next_loop_count = unique_loop_counts[i + 1]

            # Get the indices for the current loop count
            current_indices = telemetry[telemetry['loop_count'] == current_loop_count].index

            # Get the cumulative distance of the first row of the next loop count
            next_loop_start_index = telemetry[telemetry['loop_count'] == next_loop_count].index[0]
            next_loop_start_distance = telemetry.loc[next_loop_start_index, 'cumulative_distance']

            # Calculate the distance to the next lap for the current loop count
            telemetry.loc[current_indices, 'distance_to_lap'] = next_loop_start_distance - telemetry.loc[current_indices, 'cumulative_distance']

        # Handle the last loop count (set distance to lap as 0)
        last_loop_indices = telemetry[telemetry['loop_count'] == unique_loop_counts[-1]].index
        telemetry.loc[last_loop_indices, 'distance_to_lap'] = 0

        return telemetry
            

    telemetry = calculate_cumulative_distance_telemetry(telemetry)
    telemetry = calculate_distance_to_lap_telemetry(telemetry)
    telemetry = calculate_time_to_lap_telemetry(telemetry)
    
    
    # telemetry.drop(['pos_x_new', 'pos_y_new', 'pos_z_new'], axis=1, inplace=True)
    #set pos_x_new as pos_x , pos_y_new as pos_y, pos_z_new as pos_z
    telemetry.drop(['pos_x', 'pos_y', 'pos_z'], axis=1, inplace=True)
    telemetry.rename(columns={'pos_x_new': 'pos_x', 'pos_y_new': 'pos_y', 'pos_z_new': 'pos_z'}, inplace=True)
     
    max_loop_count = telemetry['loop_count'].max()
    #find index where loop_count is max
    max_loop_count_index = telemetry['loop_count'].idxmax()
    telemetry=telemetry.loc[:max_loop_count_index]
    telemetry=telemetry.dropna()
    return telemetry

In [44]:

# Calculate distance left to complete the lap
telemetry['distance_left_to_complete_lap'] = total_path_distance - telemetry['cumulative_distance']

In [45]:
telemetry

,tick,timestamp,speed_kmh,throttle,brake,rpm,fuel,charge_rem,boost,clutch,pos_x,pos_y,pos_z,loop_count,distance,cumulative_distance,distance_to_lap,time_to_lap,distance_left_to_complete_lap
0,1.0,0 days 00:00:00.008413806,0.00000,0.0,255.0,1540.0000,100.000000,100.000000,0.408447,1.0,0.0000,0.000000,0.00000,0,0.000000,0.000000,183.477914,14.439533,7357.738604
1,2.0,0 days 00:00:00.019754230,0.00000,0.0,255.0,1539.0000,100.000000,100.000000,0.408447,1.0,0.0000,0.000000,0.00000,0,0.000000,0.000000,183.477914,14.428193,7357.738604
2,3.0,0 days 00:00:00.036326945,0.00000,0.0,255.0,1538.0000,100.000000,100.000000,0.408447,1.0,0.0000,0.000000,0.00000,0,0.000000,0.000000,183.477914,14.411620,7357.738604
3,4.0,0 days 00:00:00.053150289,0.00000,0.0,255.0,1537.0000,100.000000,100.000000,0.408447,1.0,0.0000,0.000000,0.00000,0,0.000000,0.000000,183.477914,14.394796,7357.738604
4,5.0,0 days 00:00:00.069594373,0.00000,0.0,255.0,1535.0000,100.000000,100.000000,0.408447,1.0,0.0000,0.000000,0.00000,0,0.000000,0.000000,183.477914,14.378352,7357.738604
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
225008,225009.0,0 days 01:02:33.972794072,192.95880,254.0,0.0,6337.2285,9.411766,9.411766,1.789592,0.0,2.5552,0.440861,-32.86284,31,0.894229,166285.981117,3.585223,0.065272,-158928.242513
225009,225010.0,0 days 01:02:33.989597047,193.19121,255.0,0.0,6342.0015,9.411766,9.411766,1.789022,0.0,2.0482,0.424494,-32.12510,31,0.895308,166286.876426,2.689914,0.048470,-158929.137821
225010,225011.0,0 days 01:02:34.004781523,193.34897,255.0,0.0,6346.9663,9.613445,9.613445,1.788308,0.0,1.5404,0.408306,-31.38695,31,0.896096,166287.772522,1.793818,0.033285,-158930.033917
225011,225012.0,0 days 01:02:34.020729389,193.45038,0.0,0.0,6344.1780,9.613445,9.613445,1.787086,0.0,1.0336,0.392460,-30.64760,31,0.896513,166288.669035,0.897305,0.017337,-158930.930430
225012,225013.0,0 days 01:02:34.038066554,193.63179,0.0,0.0,6324.2770,9.613445,9.613445,1.785097,0.0,0.5265,0.376396,-29.90750,32,0.897305,166289.566340,0.000000,0.000000,-158931.827736

In [46]:
# import plotly.express as px

# # List of dataframes
# dfs = [df1, df2, df3, df4, df5]

# # Define a lambda function to filter each dataframe
# process_df = lambda df: df[df['speed_kmh'] ==0]

# # Iterate over each dataframe
# for idx, df in enumerate(dfs, start=1):
#     # Apply the lambda function to filter the dataframe
#     filtered_df = process_df(df)
    
#     # Create a plotly figure with speed on y-axis for filtered data and fuel on y-axis for entire data
#     fig = px.scatter(x=df.index, y=df['fuel'], labels={'x': 'Index', 'y': 'Fuel'}, title=f'Fuel for df{idx}')
#     fig.add_scatter(x=filtered_df.index, y=filtered_df['speed_kmh'], mode='markers', name='Speed < 5 km/h')
    
#     # Show the plot
#     fig.show()

### training XGboost regressor Model

In [50]:
from sklearn.model_selection import train_test_split
from xgboost import XGBRegressor
from sklearn.metrics import mean_squared_error

# Assume you have a 'lap_time' target column which you want to predict
# Create a target variable, 'lap_time', based on your telemetry data
# Here I'm assuming you can calculate it based on some criteria or as previous average lap times


# Split the data into training and testing sets
X = telemetry.drop(columns=['time_to_lap','timestamp','tick'])
y = telemetry['time_to_lap']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [51]:
# Train the model
model = XGBRegressor(objective='reg:squarederror', n_estimators=100)
model.fit(X_train, y_train)

# Make predictions
y_pred = model.predict(X_test)

# Evaluate the model
mse = mean_squared_error(y_test, y_pred)
print(f'Mean Squared Error: {mse}')

Mean Squared Error: 0.07625540839766576

In [52]:
secret = pd.read_csv('secret.csv')

In [54]:
drop_col=['packet id', 'gear_curr', 'gear_sugg','battery_max','tyre_diam_fl', 'tyre_diam_fr', 'tyre_diam_rl', 'tyre_diam_rr',
       'tyre_speed_fl', 'tyre_speed_fr', 'tyre_speed_rl', 'tyre_speed_rr',
       'time_of_day_ms', 'rpm_warning', 'rpm_rev_limiter', 'speed_top',
       'clutch_engaged', 'rpm_after_clutch', 'oil_temp','fuel capacity',
       'water_temp', 'oil_pressure', 'ride_height', 'tyre_temp_fl',
       'tyre_temp_fr', 'suspension_fl', 'suspension_fr', 'tyre_temp_rl',
       'tyre_temp_rr', 'suspension_rl', 'suspension_rr', 'gear_1', 'gear_2',
       'gear_3', 'gear_4', 'gear_5', 'gear_6', 'gear_7', 'gear_8', 'gear_9',
       'vel_x', 'vel_y', 'vel_z', 'rot_x', 'rot_y', 'rot_z', 'vel_ang_x',
       'vel_ang_y', 'vel_ang_z', 'rotx_x', 'unknown_bits_0', 'unknown_bits_1',
       'unknown_bits_2', 'unknown_float_0', 'unknown_float_1',
       'unknown_float_2', 'unknown_float_3', 'unknown_float_4',
       'unknown_float_5', 'unknown_float_6', 'unknown_float_7',
       'unknown_float_8', 'unknown_float_9', 'unknown_float_10',
       'unknown_float_11'
       ]
secret.drop(drop_col, axis=1, inplace=True)

In [64]:
def feature_for_new_data(secret):
    #['loop_count', 'distance', 'cumulative_distance', 'distance_to_lap', 'distance_left_to_complete_lap']
    secret = calculate_cumulative_distance(secret)
    secret['distance_left_to_complete_lap'] = total_path_distance - secret['cumulative_distance']
    return secret

secret = feature_for_new_data(secret)

In [61]:
secret=preprocess_data(secret)

In [62]:
secret

,tick,timestamp,speed_kmh,throttle,brake,rpm,fuel,best lap,last lap,curr,...,id,clutch,pos_x,pos_y,pos_z,loop_count,distance,cumulative_distance,distance_to_lap,time_to_lap
0,0,0 days 00:00:00.209097101,0.00000,0,0,1529.0,99.966210,-1,-1,0,...,3450,1.0,0.00000,0.000000,0.000000,0,0.000000,0.000000,16.940628,4.899788
1,1,0 days 00:00:00.209123250,0.00000,0,0,1529.0,99.966200,-1,-1,0,...,3450,1.0,0.00000,0.000000,0.000000,0,0.000000,0.000000,16.940628,4.899762
2,2,0 days 00:00:00.209143247,0.00000,0,0,1527.0,99.966194,-1,-1,0,...,3450,1.0,0.00000,0.000000,0.000000,0,0.000000,0.000000,16.940628,4.899742
3,3,0 days 00:00:00.209162102,0.00000,0,0,1525.0,99.966190,-1,-1,0,...,3450,1.0,0.00000,0.000000,0.000000,0,0.000000,0.000000,16.940628,4.899723
4,4,0 days 00:00:00.209194663,0.00000,0,0,1521.0,99.966180,-1,-1,0,...,3450,1.0,0.00000,0.000000,0.000000,0,0.000000,0.000000,16.940628,4.899691
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
52801,52801,0 days 00:14:41.592607117,280.17770,255,0,6327.0,68.849495,143826,143826,5,...,3450,0.0,-28.66378,0.000099,17.676335,5,1.298424,36762.695449,5.194851,0.071790
52802,52802,0 days 00:14:41.592636041,280.21024,255,0,6329.0,68.847800,143826,143826,5,...,3450,0.0,-27.36887,-0.001292,17.580006,5,1.298489,36763.993937,3.896362,0.071761
52803,52803,0 days 00:14:41.622236705,280.23755,255,0,6332.0,68.846110,143826,143826,5,...,3450,0.0,-26.07375,-0.002823,17.484340,5,1.298649,36765.292587,2.597713,0.042160
52804,52804,0 days 00:14:41.656063923,280.25940,255,0,6340.0,68.844410,143826,143826,5,...,3450,0.0,-24.77851,-0.004712,17.389134,5,1.298736,36766.591322,1.298977,0.008333
52805,52805,0 days 00:14:41.664396923,280.28790,255,0,6342.0,68.842710,143826,143826,5,...,3450,0.0,-23.48299,-0.006482,17.294445,6,1.298977,36767.890299,0.000000,0.000000

In [65]:
columns = X.columns
secret[columns]

,speed_kmh,throttle,brake,rpm,fuel,charge_rem,boost,clutch,pos_x,pos_y,pos_z,loop_count,distance,cumulative_distance,distance_to_lap,distance_left_to_complete_lap
0,0.00000,0,0,1529.0,99.966210,99.966210,0.408447,1.0,0.00000,0.000000,0.000000,0,0.000000,0.000000,16.940628,7357.738604
1,0.00000,0,0,1529.0,99.966200,99.966200,0.408447,1.0,0.00000,0.000000,0.000000,0,0.000000,0.000000,16.940628,7357.738604
2,0.00000,0,0,1527.0,99.966194,99.966194,0.408447,1.0,0.00000,0.000000,0.000000,0,0.000000,0.000000,16.940628,7357.738604
3,0.00000,0,0,1525.0,99.966190,99.966190,0.408447,1.0,0.00000,0.000000,0.000000,0,0.000000,0.000000,16.940628,7357.738604
4,0.00000,0,0,1521.0,99.966180,99.966180,0.408447,1.0,0.00000,0.000000,0.000000,0,0.000000,0.000000,16.940628,7357.738604
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
52801,280.17770,255,0,6327.0,68.849495,68.849495,1.808433,0.0,-28.66378,0.000099,17.676335,5,1.298424,36762.695449,5.194851,-29404.956844
52802,280.21024,255,0,6329.0,68.847800,68.847800,1.809098,0.0,-27.36887,-0.001292,17.580006,5,1.298489,36763.993937,3.896362,-29406.255333
52803,280.23755,255,0,6332.0,68.846110,68.846110,1.809368,0.0,-26.07375,-0.002823,17.484340,5,1.298649,36765.292587,2.597713,-29407.553982
52804,280.25940,255,0,6340.0,68.844410,68.844410,1.809334,0.0,-24.77851,-0.004712,17.389134,5,1.298736,36766.591322,1.298977,-29408.852718
52805,280.28790,255,0,6342.0,68.842710,68.842710,1.808691,0.0,-23.48299,-0.006482,17.294445,6,1.298977,36767.890299,0.000000,-29410.151695

In [68]:
#select the row where loop_count is max
max_loop_count_index = secret['loop_count'].idxmax()    
max_loop_count_index

52805

In [80]:
import pandas as pd

# Ensure the prediction data has the same columns as the training data
row_to_predict = secret.iloc[52805][X.columns]

# Print the row to predict after selecting columns
print("\nRow to predict (after selecting columns):")
print(row_to_predict)

# Convert each column to the appropriate type
for col in X.columns:
    row_to_predict[col] = row_to_predict[col].astype(X[col].dtype)

# Print the row to predict after data type conversion
print("\nRow to predict (after data type conversion):")
print(row_to_predict)

# Reshape the data to match the expected input format for the model
row_to_predict = row_to_predict.values.reshape(1, -1)

# Print the reshaped row to predict
print("\nRow to predict (reshaped):")
print(row_to_predict)

# Make the prediction
prediction = model.predict(row_to_predict)

# Display the prediction
print("\nPrediction:")
print(prediction)

Row to predict (after selecting columns):
speed_kmh                            280.2879
throttle                                  255
brake                                       0
rpm                                    6342.0
fuel                                 68.84271
charge_rem                           68.84271
boost                                1.808691
clutch                                    0.0
pos_x                               -23.48299
pos_y                               -0.006482
pos_z                               17.294445
loop_count                                  6
distance                             1.298977
cumulative_distance              36767.890299
distance_to_lap                           0.0
distance_left_to_complete_lap   -29410.151695
Name: 52805, dtype: object

Row to predict (after data type conversion):
speed_kmh                            280.2879
throttle                                255.0
brake                                     0.0
rpm                                    6342.0
fuel                                 68.84271
charge_rem                           68.84271
boost                                1.808691
clutch                                    0.0
pos_x                               -23.48299
pos_y                               -0.006482
pos_z                               17.294445
loop_count                                  6
distance                             1.298977
cumulative_distance              36767.890299
distance_to_lap                           0.0
distance_left_to_complete_lap   -29410.151695
Name: 52805, dtype: object

Row to predict (reshaped):
[[280.2879 255.0 0.0 6342.0 68.84271 68.84271 1.8086908 0.0
  -23.482989999999987 -0.006482000000001875 17.294444999999996 6
  1.2989769859474138 36767.890299479965 0.0 -29410.151695078686]]

Prediction:
[2.0559506]